version: '3.8'

services:
    url_shortener:
        build: .
        container_name: url-shortener
        ports:
            - '4200:4200'
        depends_on:
            - mongodb
            - redis
        environment:
            MODE: dev
            PORT: 4200
            HOST: http://localhost:4200
            JWT_ACCESS_SECRET: access-secret
            JWT_ACCESS_EXPIRES: 1d
            JWT_REFRESH_SECRET: refresh-secret
            JWT_REFRESH_EXPIRES: 7d
            SENTRY_DSN: https://b4caa5b3369db8c83165cd055a710627@o4507809720172544.ingest.de.sentry.io/4507809721942096
            MONGODB_URL: mongodb://mongodb:27017/nest
            REDIS_PASSWORD: Z6b0BpkLIZG2FlUM2RLVfrom3TNokbkz
            REDIS_HOST: redis
            REDIS_PORT: 6379

    mongodb:
        image: mongo:6.0
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

volumes:
    mongo_data:
    redis_data:
